
package es.uned.scc.grados.appdist.trabajos.ws.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SignalGeneratorWS", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SignalGeneratorWS {


    /**
     * 
     * @return
     *     returns es.uned.scc.grados.appdist.trabajos.ws.soap.OperationInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "start", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.Start")
    @ResponseWrapper(localName = "startResponse", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.StartResponse")
    @Action(input = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/startRequest", output = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/startResponse")
    public OperationInfo start();

    /**
     * 
     * @return
     *     returns es.uned.scc.grados.appdist.trabajos.ws.soap.OperationInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "stop", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.Stop")
    @ResponseWrapper(localName = "stopResponse", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.StopResponse")
    @Action(input = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/stopRequest", output = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/stopResponse")
    public OperationInfo stop();

    /**
     * 
     * @return
     *     returns es.uned.scc.grados.appdist.trabajos.ws.soap.OperationInfo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isRunning", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.IsRunning")
    @ResponseWrapper(localName = "isRunningResponse", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.IsRunningResponse")
    @Action(input = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/isRunningRequest", output = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/isRunningResponse")
    public OperationInfo isRunning();

    /**
     * 
     * @return
     *     returns es.uned.scc.grados.appdist.trabajos.ws.soap.SignalParameters
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignalParameters", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.GetSignalParameters")
    @ResponseWrapper(localName = "getSignalParametersResponse", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.GetSignalParametersResponse")
    @Action(input = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/getSignalParametersRequest", output = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/getSignalParametersResponse")
    public SignalParameters getSignalParameters();

    /**
     * 
     * @param signalParameters
     */
    @WebMethod
    @RequestWrapper(localName = "setSignalParameters", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.SetSignalParameters")
    @ResponseWrapper(localName = "setSignalParametersResponse", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.SetSignalParametersResponse")
    @Action(input = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/setSignalParametersRequest", output = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/setSignalParametersResponse")
    public void setSignalParameters(
        @WebParam(name = "signal_parameters", targetNamespace = "")
        SignalParameters signalParameters);

    /**
     * 
     * @return
     *     returns es.uned.scc.grados.appdist.trabajos.ws.soap.SignalData
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSignalValue", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.GetSignalValue")
    @ResponseWrapper(localName = "getSignalValueResponse", targetNamespace = "http://ws.trabajos.appdist.grados.scc.uned.es/", className = "es.uned.scc.grados.appdist.trabajos.ws.soap.GetSignalValueResponse")
    @Action(input = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/getSignalValueRequest", output = "http://ws.trabajos.appdist.grados.scc.uned.es/SignalGeneratorWS/getSignalValueResponse")
    public SignalData getSignalValue();

}
